commit 107f9c78be7e929f3036451b4e3828a2ce0fcb72 (refs/changes/40/2340/1)
Author: Pedro Palazon Candel <pedro@joyent.com>
Date:   2017-08-07T16:22:37+02:00 (2 years, 2 months ago)
    
    TOOLS-1832 sdcadm: incorrect UsageError invocation throws exception

diff --git a/lib/post-setup/ha-manatee.js b/lib/post-setup/ha-manatee.js
index 8b7cba5..2fc1ee6 100644
--- a/lib/post-setup/ha-manatee.js
+++ b/lib/post-setup/ha-manatee.js
@@ -17,6 +17,8 @@ var sprintf = require('extsprintf').sprintf;
 var vasync = require('vasync');
 var assert = require('assert-plus');
 
+var util = require('util');
+
 var common = require('../common');
 var svcadm = require('../svcadm');
 var errors = require('../errors');
@@ -319,10 +321,10 @@ function do_ha_manatee(subcmd, opts, args, cb) {
             }
             self.progress('Verifying 2nd manatee server');
             if (sry.server_uuid !== opts.servers[0]) {
-                return next(new errors.UsageError(
+                return next(new errors.UsageError(util.format(
                         'The server specified for manatee1 \'%s\' is not ' +
                         'the same than the server where it has been created ' +
-                        '\'%s\'', opts.servers[0], sry.server_uuid));
+                        '\'%s\'', opts.servers[0], sry.server_uuid)));
             }
             return next();
         },
